swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: localhost:5000
basePath: /api/v1
schemes:
  - http
paths:
  /cameras:
    get:
      summary: Can be used to get ALL camera's
      produces:
        - application/json
      responses:
        200:
          description: Returns a list of cameras.
          schema:
            $ref: '#/components/schemas/Cameras'
  /cameras/{camera_id}:
    get:
      parameters:
        - in: path
          name: camera_id
          type: integer
          required: true
          description: Camera id 
      summary: Can be used to search for a specific camera id
      produces:
        - application/json
      responses:
        200:
          description: Returns a single camera or multiple camera's by id
          schema:
            $ref: '#/components/schemas/Cameras'

components:
  schemas:
    Cameras:
      type: array
      items: 
        $ref: '#/components/schemas/Camera'
    Camera:
      type: object
      properties:
        Number:
          type: string
        Camera:
          type: string
        Latitude:
          type: string
        Longitude:
          type: string
      required:
        - Number
        - Camera
        - Latitude
        - Longtitude
